name: Build Docker Image & Push to Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout git repository
      uses: actions/checkout@v4

    - name: build the Docker image
    #  run: docker build . --file Dockerfile --tag allinone-tom.online/fangxiaoyuan/robot-for-fxy:$(date +%s)
      run: docker build . --file Dockerfile --tag allinone-tom.online/fangxiaoyuan/robot-for-fxy:v1.0.0

    - name: push docker images
      run: docker push allinone-tom.online/fangxiaoyuan/robot-for-fxy:v1.0.0
