name: Build Docker Image & Push to Hub
run-name: "test run name"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout git repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name:  show docker images
      run: docker image ls -a
